#!/bin/sh

# X settings: no bell, repeat rate, keyboard map
setxkbmap 'us(altgr-intl)'
xset r rate 400 40
xset -b

# Start task bar, status bar, and screensaver
tint2&
xscreensaver -no-splash&
($HOME/bin/i3status.sh | dzen2 -e "onstart=lower" -ta r -xs 1 -fn Terminus -h 20 -y 1060) &
($HOME/bin/i3status.sh | dzen2 -e "onstart=lower" -ta r -xs 2 -fn Terminus -h 20 -y 1060) &

# Load the background and start the compositor
feh --no-xinerama --bg-center $HOME/Pictures/xplanet-out.png
compton&
